services:
  feishin:
    container_name: feishin
    image: "ghcr.io/jeffvli/feishin:latest"
    restart: unless-stopped
    environment:
      - SERVER_NAME=jellyfin
      - SERVER_LOCK=false
      - SERVER_TYPE=jellyfin
      - SERVER_URL=http://localhost:8096
      - LEGACY_AUTHENTICATION=false
      - ANALYTICS_DISABLED=false
    ports:
      - 9180:9180
    networks:
      - warp
  musicseerr:
    image: ghcr.io/habirabbu/musicseerr:latest
    container_name: musicseerr
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8688
      - TZ=Etc/UTC
    ports:
      - "8688:8688"
    volumes:
      - /mnt/media/arr/Lidarr/music:/music:ro
      - ./config:/app/config
      - ${ARRPATH}cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8688/health"]
      interval: 30s
      timeout: 10s
      start_period: 15s
      retries: 3
    networks:
      - warp
  explo:
    image: ghcr.io/lumepart/explo:latest
    restart: unless-stopped
    container_name: explo
    ports:
      - "7288:7288"
    volumes:
      - ./.env:/opt/explo/.env
      - ./config:/opt/explo/config
      - /mnt/media/arr/Lidarr/music:/data/
    environment:
      - TZ=${TZ}
      - WEB_UI=${WEB_UI}
      - UI_USERNAME=${UI_USERNAME}
      - UI_PASSWORD=${UI_PASSWORD}
    networks:
      - warp
networks:
  warp:
    driver: bridge
    name: arr_warp
