services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
      - /var/lib/tailscale/certs:/etc/nginx/certs:ro ##new shii
    environment:
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - IMMICH_HOST=${IMMICH_HOST}
      - IMMICH_PORT=${IMMICH_PORT}
